services:
  translate-model:
    provider:
      type: model
      options:
        model: ${TRANSLATE_MODEL:-docker.io/ai/gemma3:4B-F16}

  ocr-model:
    provider:
      type: model
      options:
        model: ${OCR_MODEL:-docker.io/ai/gemma3n:2B-F16}
